In [1]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [5]:
print(benimDizim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
print(benimDizim[5])

5


In [8]:
benimDizim[5:9]

array([5, 6, 7, 8])

In [9]:
benimDizim[3:8] = -5   # 3 ile 7 arasındaki degeri -5 yapar

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
slicingDizisi = baskaDizi[4:9]

In [13]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [18]:
slicingDizisi[:] = 700  # Ana veriden parça olarak aldıgımız kısmı degişince ana veride değişiyor bu yüzden ana veririnn kopyası ile çalış

In [19]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [20]:
slicingDizisi  

array([700, 700, 700, 700, 700])

In [25]:
benimListem = np.arange(10,100,10)

In [26]:
benimListem

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
benimMatrixDizim = benimListem.reshape(3,3)

In [28]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
benimMatrixDizim[0]

array([10, 20, 30])

In [31]:
benimMatrixDizim[1][2]  # 1 Satir 2 Sütun

np.int64(60)

In [32]:
benimMatrixDizim[1,2] # üstteki kodun aynısı   column = sütun 

np.int64(60)

In [37]:
benimMatrixDizim[1:,2]  # 1. satır ve sonrasını getirir 

array([60, 90])

In [38]:
yeniListe = np.arange(0,25)

In [42]:
yeniMatrix = yeniListe.reshape(5,5)

In [43]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
yeniMatrix[[0,2,4]]  # 0 , 2 ve 4. index satırları yazdırır

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operasyonlar Top Çıkarma falan

In [47]:
yeniDizi = np.random.randint(1,100,20)

In [48]:
yeniDizi

array([86, 85, 72, 43, 20, 57, 30, 90, 18, 70,  9, 53, 23, 95,  5, 93, 78,
       65, 16, 31], dtype=int32)

In [49]:
yeniDizi > 24

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True, False,  True, False,  True,  True,  True,
       False,  True])

In [50]:
sonucDizi = yeniDizi > 24

In [51]:
sonucDizi

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True, False,  True, False,  True,  True,  True,
       False,  True])

In [53]:
yeniDizi[sonucDizi] # Sadece 24den büyükleri filtreler

array([86, 85, 72, 43, 57, 30, 90, 70, 53, 95, 93, 78, 65, 31],
      dtype=int32)

In [54]:
sonDizi = np.arange(0,24)

In [55]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [56]:
sonDizi* sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [57]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])